
import React from 'react';
import { PublicNavigation } from './PublicNavigation';
import { ArrowLeft } from 'lucide-react';

interface TermsAndConditionsProps {
  onBack: () => void;
  onLogin: () => void;
  onSignup: () => void;
  onPricing: () => void;
}

export const TermsAndConditions: React.FC<TermsAndConditionsProps> = ({ onBack, onLogin, onSignup, onPricing }) => {
  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950 font-sans text-slate-900 dark:text-white animate-fade-in selection:bg-[#0500e2] selection:text-white">
      <PublicNavigation 
        onLanding={onBack}
        onLogin={onLogin}
        onSignup={onSignup}
        onPricing={onPricing}
        activePage="landing" // Keep generic or add 'terms' to types if strictly needed, but landing style works
      />

      <div className="max-w-4xl mx-auto px-6 pt-32 pb-20">
        <button 
            onClick={onBack}
            className="mb-8 flex items-center gap-2 text-slate-500 hover:text-[#0500e2] transition-colors font-medium group"
        >
            <ArrowLeft size={20} className="group-hover:-translate-x-1 transition-transform" /> Back to Home
        </button>

        <div className="bg-white dark:bg-slate-900 rounded-[2rem] shadow-sm border border-slate-200 dark:border-slate-800 p-8 md:p-12">
            <h1 className="text-3xl md:text-4xl font-serif font-bold mb-2">Terms and Conditions</h1>
            <p className="text-slate-500 dark:text-slate-400 mb-10 text-sm">Last Updated: February 24, 2025</p>

            <div className="space-y-8 text-slate-600 dark:text-slate-300 leading-relaxed">
                <section>
                    <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-4">1. Introduction</h2>
                    <p>
                        Welcome to RevuQA AI. By accessing or using our website and services (collectively, the "Service"), 
                        you agree to be bound by these Terms and Conditions ("Terms"). If you disagree with any part of the terms, 
                        you may not access the Service.
                    </p>
                </section>

                <section>
                    <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-4">2. Use License</h2>
                    <p className="mb-4">
                        Permission is granted to temporarily download one copy of the materials (information or software) on RevuQA AI's 
                        website for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, 
                        and under this license you may not:
                    </p>
                    <ul className="list-disc pl-5 space-y-2">
                        <li>modify or copy the materials;</li>
                        <li>use the materials for any commercial purpose, or for any public display (commercial or non-commercial);</li>
                        <li>attempt to decompile or reverse engineer any software contained on RevuQA AI's website;</li>
                        <li>remove any copyright or other proprietary notations from the materials; or</li>
                        <li>transfer the materials to another person or "mirror" the materials on any other server.</li>
                    </ul>
                </section>

                <section>
                    <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-4">3. AI & Data Usage</h2>
                    <p>
                        Our Service utilizes artificial intelligence to analyze customer support interactions. By using the Service, 
                        you acknowledge that:
                    </p>
                    <ul className="list-disc pl-5 space-y-2 mt-4">
                        <li>You have the necessary rights and consents to process the audio and text data you upload.</li>
                        <li>Automated scoring and feedback are generated by AI and should be reviewed by human supervisors for critical decisions.</li>
                        <li>We prioritize data security and do not use your proprietary customer data to train our public models without explicit consent.</li>
                    </ul>
                </section>

                <section>
                    <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-4">4. Billing and Credits</h2>
                    <p>
                        Services are billed based on a credit system. Credits are purchased in advance or via subscription. 
                        Unused credits may roll over depending on your specific plan terms. Refunds are processed at our sole discretion 
                        within 14 days of purchase if no usage has occurred.
                    </p>
                </section>

                <section>
                    <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-4">5. Disclaimer</h2>
                    <p>
                        The materials on RevuQA AI's website are provided on an 'as is' basis. RevuQA AI makes no warranties, 
                        expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, 
                        implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement 
                        of intellectual property or other violation of rights.
                    </p>
                </section>

                <section>
                    <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-4">6. Limitations</h2>
                    <p>
                        In no event shall RevuQA AI or its suppliers be liable for any damages (including, without limitation, 
                        damages for loss of data or profit, or due to business interruption) arising out of the use or inability 
                        to use the materials on RevuQA AI's website.
                    </p>
                </section>

                <section>
                    <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-4">7. Governing Law</h2>
                    <p>
                        These terms and conditions are governed by and construed in accordance with the laws of Delaware, USA, 
                        and you irrevocably submit to the exclusive jurisdiction of the courts in that State or location.
                    </p>
                </section>
            </div>
        </div>
      </div>
    </div>
  );
};
